### ISSUE TITLE
No matching distribution found for flask-ipywidgets

### ISSUE THREAD

**Issue by lincolnfrias** [maartenbreddels/flask-ipywidgets#1]
Well, I realize that I am a very early anxious adopter, but just to let you know, `pip install flask-ipywidgets`  is giving: 

    Could not find a version that satisfies the requirement flask-ipywidgets (from versions: )
    No matching distribution found for flask-ipywidgets

**Comment by maartenbreddels** [comment]
I didn't release it on pypi yet, as of 2 minutes ago, so please try again and let me know if it works.

**Comment by lincolnfrias** [comment]
Now the installation went ok. But `python -m flask_ipywidgets.example1` was returning:

    ModuleNotFoundError: No module named 'flask_sockets'

I installed `flask_sockets` with pip. But now `python -m flask_ipywidgets.example1` just hangs and there is nothing on localhost:5000.

**Comment by maartenbreddels** [comment]
Indeed, flask_sockets is missing as a dependency. I tried it here on macos and linux in a clean env, and it works: 
 * `$pip install flask_ipywidget flask_sockets`
 * `$python -m flask_ipywidgets.example1`
Open http://localhost:5000 and you should at least see stuff printed out on the console, maybe you used https?.

**Comment by lincolnfrias** [comment]
Ok, I'll try a clean env then. 
So, I'm closing this. Thanks a lot!
