### ISSUE TITLE
ipywidgets_server now refers to voila

### ISSUE THREAD

**Issue by jf---** [maartenbreddels/flask-ipywidgets#13]
see [this discussion](https://github.com/pbugnion/ipywidgets_server/issues/48)
should `flask-ipywidgets` also deprecate and redirect to [voila](https://github.com/QuantStack/voila)?

**Comment by maartenbreddels** [comment]
No I don't think so, flask-ipywidgets does not have the same model as voila, it does not use kernels/notebooks for execution. As voila moves on, some of the changes can go into flask-ipywidgets, but they have different visions. Voila serves notebooks, and executes them using a kernel. This projects tries to integrate widgets into an existing flask server, some overlap, but a significant difference.

**Comment by jf---** [comment]
> some overlap, but a significant difference.

clear as day. thx Maarten
