### ISSUE TITLE
Combobox ipywidget

### ISSUE THREAD

**Issue by paraguz1** [maartenbreddels/flask-ipywidgets#15]
I'm trying to use a Combobox ipywidget. I just reproduced the first example example1 trying to use a Combobox but it is not working. I do not know if I shoud adapt the HTML template?
The idea is to use a Combobox and a widget figure produced with plotly (a Sankey Diagram).
The combobox will be used to filter data a update the Sankey Diagram. But I think the current templates are not adapted for this?

filter_canal = Combobox(options= ['Total', 'Contact center'], 
                                   default_value = ['Total'], 
                                   allow_none =  True,
                                   description = 'Canal',
                                   value = 'Total')
vbox = widgets.VBox([filter_canal, filter_canal])

return render_template('example1.html', slider1= filter_canal ,slider2 = filter_canal, widgets=vbox)

Thank you for your repository, I tested the examples and look great!

**Comment by maartenbreddels** [comment]
Superseded by [https://github.com/widgetti/solara/](https://github.com/widgetti/solara/)
