### ISSUE TITLE
looks like JS deps arent building correct anymore?

### ISSUE THREAD

**Issue by jf---** [maartenbreddels/flask-ipywidgets#4]
just to make sure, I've created a new `conda env` and update `npm`; however, it looks like the `JS` dependencies arent correctly installing anymore.

The issue seems that the directory layout and filenames of the installed `JS` dependencies have changed. I ran `npm install && npm run build` with the `js` directory, which completed without errors.

Rather than finding `require.min.js` in `flask_widgets/static` the directory layout seems pretty different:

![image](https://user-images.githubusercontent.com/620988/43370824-7a5b7416-9386-11e8-842c-cf37b5202e9a.png)

**Comment by maartenbreddels** [comment]
which node version are you using? and do you get it from conda-forge?

**Comment by jf---** [comment]
Node is version 9.5.0... 
Thx for hinting at conda-forge, indeed nodejs wasn't the conda installed version.

**Comment by maartenbreddels** [comment]
In the template it said:
```html
        <script
            data-main="/static/main"
            src="/static/require.min.js"
            integrity="sha256-Ae2Vz/4ePdIu6ZyI/5ZGsYnb+m0JlOmKPjt6XZ9JJkA="
            crossorigin="anonymous">
        </script>
```
Which should load `static/main.js`, which sets
```
requirejs.config({
    baseUrl: '/static/dist/'
})
```
Which is I think what you were missing.
